//! `rift-lint schema` (issue #1342): the imposter grammar as a JSON Schema, generated by the
//! engine crate from its own config types and checked in at
//! `sdk-conformance/schema/imposter.schema.json`, where the SDK-conformance tarball ships it.
//!
//! This crate only prints it. The drift test below is what keeps the checked-in copy current:
//! it runs under `--all-features` in CI and fails with the regenerate command when the two differ.

/// The schema as the checked-in file holds it: pretty-printed, trailing newline.
///
/// # Errors
/// Only if the generated value cannot be serialized, which a `serde_json::Value` never is in
/// practice; propagated rather than defaulted so the caller never writes an empty file.
pub fn imposter_schema_text() -> Result<String, serde_json::Error> {
    let mut text = serde_json::to_string_pretty(&rift_mock_core::schema::imposter_schema())?;
    text.push('\n');
    Ok(text)
}

#[cfg(test)]
mod tests {
    use super::imposter_schema_text;
    use crate::CHECKED_IN_SCHEMA;
    use std::path::Path;

    /// The checked-in schema is byte-for-byte what this engine build generates. Any change to a
    /// config type's serde shape lands here first, as a failing test naming the command to run.
    #[test]
    fn checked_in_schema_matches_the_generated_one() {
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(CHECKED_IN_SCHEMA);
        let checked_in = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let generated = imposter_schema_text().expect("serializes");
        if checked_in != generated {
            let checked: serde_json::Value = serde_json::from_str(&checked_in).expect("JSON");
            let wanted: serde_json::Value = serde_json::from_str(&generated).expect("JSON");
            let mut differing = Vec::new();
            diff("", &checked, &wanted, &mut differing);
            panic!(
                "sdk-conformance/schema/imposter.schema.json is stale at {}; regenerate with:\n  \
                 cargo run -p rift-lint --features schema -- schema --out \
                 sdk-conformance/schema/imposter.schema.json",
                if differing.is_empty() {
                    "(formatting only)".to_owned()
                } else {
                    differing.join(", ")
                }
            );
        }
    }

    /// The paths at which two JSON values differ, shallowest first.
    fn diff(path: &str, a: &serde_json::Value, b: &serde_json::Value, out: &mut Vec<String>) {
        match (a, b) {
            (serde_json::Value::Object(a), serde_json::Value::Object(b)) => {
                for key in a.keys().chain(b.keys().filter(|k| !a.contains_key(*k))) {
                    let child = format!("{path}/{key}");
                    match (a.get(key), b.get(key)) {
                        (Some(x), Some(y)) => diff(&child, x, y, out),
                        _ => out.push(child),
                    }
                }
            }
            (serde_json::Value::Array(a), serde_json::Value::Array(b)) if a.len() == b.len() => {
                for (i, (x, y)) in a.iter().zip(b).enumerate() {
                    diff(&format!("{path}/{i}"), x, y, out);
                }
            }
            _ if a != b => out.push(if path.is_empty() {
                "/".to_owned()
            } else {
                path.to_owned()
            }),
            _ => {}
        }
    }

    #[test]
    fn diff_names_the_differing_paths() {
        let mut out = Vec::new();
        diff(
            "",
            &serde_json::json!({ "a": 1, "b": { "c": [1, 2] }, "d": 3 }),
            &serde_json::json!({ "a": 1, "b": { "c": [1, 3] }, "e": 3 }),
            &mut out,
        );
        assert_eq!(out, ["/b/c/1", "/d", "/e"]);
    }
}
