/* Rift C-ABI (issues #204, #343). GENERATED by cbindgen — do not edit by hand.
   Regenerate + verify with scripts/verify-ffi-cdylib.sh. */

#ifndef RIFT_FFI_H
#define RIFT_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle: a Tokio runtime (on its own threads), the engine it drives, and — once
 * [`rift_serve_admin`] is called — the in-process admin/metrics plane serving over that engine.
 */
typedef struct RiftHandle RiftHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Start the engine. Returns an opaque handle, or null if the runtime could not be created.
 *
 * Installs the process-wide rustls `ring` crypto provider (idempotently) so HTTPS imposters
 * created through this handle work without the host installing a provider itself (issue #343).
 */
RiftHandle *rift_start(void);

/**
 * Create an imposter from a JSON config. Returns its port, or `0` on any error
 * (null handle/json, malformed config, or bind failure — `0` is never a live imposter port).
 *
 * # Safety
 * `h` must be a live handle and `json` a valid C string (or null).
 */
uint16_t rift_create_imposter(RiftHandle *h, const char *json);

/**
 * Replace all stubs on `port` from a JSON array. Returns `0` on success, `-1` on any error.
 *
 * # Safety
 * `h` must be a live handle and `json` a valid C string (or null).
 */
int32_t rift_replace_stubs(RiftHandle *h, uint16_t port, const char *json);

/**
 * Remove all imposters. Returns `0` on success, `-1` if the handle is null.
 *
 * # Safety
 * `h` must be a live handle (or null).
 */
int32_t rift_delete_all(RiftHandle *h);

/**
 * Delete one imposter, freeing its port. Returns `0` on success, `-1` on any error
 * (null handle or no imposter on `port`). Issue #343.
 *
 * # Safety
 * `h` must be a live handle (or null).
 */
int32_t rift_delete_imposter(RiftHandle *h, uint16_t port);

/**
 * Return the recorded requests for `port` as a JSON array string the caller must free with
 * [`rift_free`]. Returns null on any error (null/unknown handle or port, or encode failure).
 *
 * # Safety
 * `h` must be a live handle (or null).
 */
char *rift_recorded(RiftHandle *h, uint16_t port);

/**
 * Return the stub-overlap analysis warnings for `port` as a JSON array string the caller must free
 * with [`rift_free`] (issue #423). This gives embedded / direct C-ABI consumers the config-lint
 * warnings (duplicate/shadowed/catch-all stubs) that previously only the HTTP admin layer
 * surfaced. The warnings are computed once on stub mutation and cached, so this is a cheap read.
 * Returns null on any error (null/unknown handle or port, or encode failure).
 *
 * # Safety
 * `h` must be a live handle (or null).
 */
char *rift_stub_warnings(RiftHandle *h, uint16_t port);

/**
 * Verify recorded requests against a predicate set server-side (issue #494), returning the JSON
 * `{"matched","total","requests"?,"closest"?}` envelope the caller frees with [`rift_free`]. The
 * `body_json` is the same `POST /imposters/{port}/verify` body:
 * `{"predicates":[…],"flowId"?,"includeRequests"?,"includeClosest"?}`. This lets an embedded SDK
 * count matches through the engine's one true predicate evaluator (including `xpath`/`inject`,
 * impractical client-side) instead of shipping the whole journal over the wire. Unlike the admin
 * HTTP endpoint, an `inject` predicate is NOT gated here: the direct C-ABI caller is the trusted
 * in-process embedder, matching how `rift_replace_stubs` accepts inject stubs.
 *
 * Returns null on any error (null/unknown handle or port, invalid JSON, a failing `inject`
 * predicate, or encode failure), with the reason in `rift_last_error`.
 *
 * # Safety
 * `h` must be a live handle (or null); `body_json` must be null or a valid C string.
 */
char *rift_verify(RiftHandle *h, uint16_t port, const char *body_json);

/**
 * Get a scenario/flow-state value as a JSON envelope `{"found","flowId","key","value"}` the caller
 * frees with [`rift_free`]. `found` disambiguates an absent key from a failure: a missing key is a
 * non-error outcome (`{"found":false,"value":null}`), while a null pointer is returned **only** on a
 * genuine error (unknown handle/port or encode failure, reason in `rift_last_error`) — matching
 * [`rift_recorded`] and the rc-returning calls, where null/`-1` means error alone.
 *
 * # Safety
 * `h` must be a live handle (or null); `flow_id`/`key` must be null or valid C strings.
 */
char *rift_flow_state_get(RiftHandle *h,
                          uint16_t port,
                          const char *flow_id,
                          const char *key);

/**
 * Set a scenario/flow-state value from a bare JSON value (`value_json`). Returns `0` on success,
 * `-1` on any error.
 *
 * # Safety
 * `h` must be a live handle (or null); the string pointers must be null or valid C strings.
 */
int32_t rift_flow_state_put(RiftHandle *h,
                            uint16_t port,
                            const char *flow_id,
                            const char *key,
                            const char *value_json);

/**
 * Delete a scenario/flow-state key. Returns `0` on success, `-1` on any error.
 *
 * # Safety
 * `h` must be a live handle (or null); the string pointers must be null or valid C strings.
 */
int32_t rift_flow_state_delete(RiftHandle *h, uint16_t port, const char *flow_id, const char *key);

/**
 * Register a stub scoped to `flow_id` (its `space` is set from `flow_id`, ignoring any `space`
 * in the JSON, mirroring the admin path). Returns `0` on success, `-1` on any error.
 *
 * # Safety
 * `h` must be a live handle (or null); the string pointers must be null or valid C strings.
 */
int32_t rift_space_add_stub(RiftHandle *h,
                            uint16_t port,
                            const char *flow_id,
                            const char *stub_json);

/**
 * List a space's scoped stubs as JSON `{"space","stubs":[…]}` the caller frees with
 * [`rift_free`], or null on error.
 *
 * # Safety
 * `h` must be a live handle (or null); `flow_id` must be null or a valid C string.
 */
char *rift_space_list_stubs(RiftHandle *h, uint16_t port, const char *flow_id);

/**
 * Tear down a space in one call (its scoped stubs, recorded requests, and scenario state — never
 * a global reset). Returns `0` on success, `-1` on any error.
 *
 * # Safety
 * `h` must be a live handle (or null); `flow_id` must be null or a valid C string.
 */
int32_t rift_space_delete(RiftHandle *h, uint16_t port, const char *flow_id);

/**
 * The requests recorded for `flow_id` — filtered by the space's resolved flow-id, the same
 * resolution the space-inspection view uses (the header-filtered `received`, issue #201) — as a
 * JSON array the caller frees with [`rift_free`], or null on error.
 *
 * # Safety
 * `h` must be a live handle (or null); `flow_id` must be null or a valid C string.
 */
char *rift_space_recorded(RiftHandle *h, uint16_t port, const char *flow_id);

/**
 * Start the intercept/TLS-MITM forward-proxy listener on this handle's runtime. The intercept CA
 * is loaded from `caCertPath`/`caKeyPath` when both are supplied (letting independent instances
 * share a committed trust anchor), and generated fresh otherwise. Returns JSON
 * `{"interceptPort":<u16>,"interceptUrl":"http://<bind-host>:<port>"}` the caller frees with
 * [`rift_free`], or null on error (bad JSON, half-configured CA pair, CA load failure, bind
 * failure, or already started — one listener per handle). `interceptUrl` reflects the bound
 * address (the configured `host`, loopback by default; a `0.0.0.0` bind surfaces verbatim, so
 * dial a concrete interface). `options_json`:
 * `{"host":"127.0.0.1","port":0,"caCertPath":"ca.pem","caKeyPath":"ca.key"}` (port 0 =
 * OS-assigned; CA paths optional, both-or-neither); pass null or `{}` for defaults.
 *
 * # Safety
 * `h` must be a live handle (or null); `options_json` must be null or a valid C string.
 */
char *rift_start_intercept(RiftHandle *h, const char *options_json);

/**
 * Add one intercept rule (a bare object) or many (a JSON array) — same shape the
 * `/intercept/rules` admin route accepts. Returns `0` on success, `-1` on any error.
 *
 * # Safety
 * `h` must be a live handle (or null); `rules_json` must be null or a valid C string.
 */
int32_t rift_intercept_add_rules(RiftHandle *h, const char *rules_json);

/**
 * Remove all intercept rules. Returns `0` on success, `-1` on any error.
 *
 * # Safety
 * `h` must be a live handle (or null).
 */
int32_t rift_intercept_clear_rules(RiftHandle *h);

/**
 * List the current intercept rules as a JSON array the caller frees with [`rift_free`], or null
 * on error (null handle, intercept not started, or encode failure).
 *
 * # Safety
 * `h` must be a live handle (or null).
 */
char *rift_intercept_list_rules(RiftHandle *h);

/**
 * The intercept CA certificate as PEM, the caller frees with [`rift_free`], or null on error
 * (null handle, or intercept not started).
 *
 * # Safety
 * `h` must be a live handle (or null).
 */
char *rift_intercept_ca_pem(RiftHandle *h);

/**
 * Write a truststore for the intercept CA to `out_path` — a truststore is binary, so it is
 * written to a file (the format a JVM `trustStore` consumes directly) rather than returned as a
 * C string. `format` is `"pkcs12"` or `"jks"`; `password` may be null for the default
 * `"changeit"`. Returns `0` on success, `-1` on any error.
 *
 * # Safety
 * `h` must be a live handle (or null); the string pointers must be null or valid C strings.
 */
int32_t rift_intercept_export_truststore(RiftHandle *h,
                                         const char *format,
                                         const char *password,
                                         const char *out_path);

/**
 * Start the real admin API (and, if `metricsPort` is given, the metrics server) in-process on
 * this handle's runtime, serving over this handle's manager (issue #343).
 *
 * `options_json` (null or `{}` uses all defaults; every field optional):
 * `{"host":"127.0.0.1","port":0,"apiKey":null,"metricsPort":null,"configFile":null,"config":null}`.
 * `configFile` is loaded and wired as the reload source (like `--configfile`); `config` is an
 * inline `{"imposters":[...]}`. Both are applied via `apply_config` (a reconcile, so a per-port
 * bind failure is reported in the apply report rather than aborting mid-load). They don't
 * compose: passing both leaves only the inline set (its reconcile deletes the rest) — pass one.
 *
 * Returns (caller frees) `{"adminPort":49321,"adminUrl":"http://127.0.0.1:49321","metricsPort":null}`,
 * or null on error (bad JSON, bind failure, or already serving — one admin plane per handle).
 *
 * # Safety
 * `h` must be a live handle and `options_json` null or a valid C string.
 */
char *rift_serve_admin(RiftHandle *h,
                       const char *options_json);

/**
 * Incrementally reconcile the manager toward the given config (issue #316/#343). Input is
 * `{"imposters":[...]}` or a bare array. Returns (caller frees) a report with the same field
 * names as `POST /admin/reload`:
 * `{"created":[..],"replaced":[..],"stubPatched":[..],"deleted":[..],"failed":[{"port":0,"error":".."}]}`.
 * Returns null only on invalid input / up-front validation failure — then nothing was mutated
 * and the reason is in [`rift_last_error`]. Partial per-port failures come back in `failed`.
 *
 * # Safety
 * `h` must be a live handle and `config_json` a valid C string (or null).
 */
char *rift_apply_config(RiftHandle *h,
                        const char *config_json);

/**
 * Build identity as a STATIC JSON string — never freed; probe this symbol to detect a v2 library
 * (issue #343). `{"version":"..","commit":"<sha>|null","builtAt":"<iso8601>|null","features":[..]}`.
 * `commit`/`builtAt` are `null` unless stamped at build time (issue #344).
 */
const char *rift_build_info(void);

/**
 * Take this thread's last-error message (set by a failed `rift_*` call), or null if none.
 * Reading it clears it; the caller frees the returned string with [`rift_free`] (issue #343).
 */
char *rift_last_error(void);

/**
 * Free a string previously returned by a `rift-ffi` function. Null is a no-op.
 *
 * # Safety
 * `p` must be null or a pointer returned by a `rift-ffi` function (never [`rift_build_info`],
 * whose static string must not be freed) and not yet freed.
 */
void rift_free(char *p);

/**
 * Stop the engine: shut down the admin/metrics listeners first, then gracefully shut down all
 * imposters, and drop the handle + runtime. Null is a no-op. The handle must not be used after.
 *
 * # Safety
 * `h` must be null or a pointer returned by [`rift_start`] and not previously stopped.
 */
void rift_stop(RiftHandle *h);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RIFT_FFI_H */
